module.exports = {
    "CONGRESS_MEMBERS_FETCH": "CONGRESS_MEMBERS_FETCH",
    "CONGRESS_MEMBERS_SUCCESS": "CONGRESS_MEMBERS_SUCCESS",
    "CONGRESS_MEMBERS_ERROR": "CONGRESS_MEMBERS_ERROR",
    "GET_MEMBER_FETCH": "GET_MEMBER_FETCH",
    "GET_MEMBER_SUCCESS": "GET_MEMBER_SUCCESS",
    "GET_MEMBER_ERROR": "GET_MEMBER_ERROR",
};